### ISSUE TITLE
Nested folder support

### ISSUE THREAD

**Issue by r9isgod8** [anadius/gd-efc#1]
Hi, the tool works flawless with single level google drive folders but if we wish to copy multi-level drive folders from one account to another the tool can't find the files inside. One example would be this link https://drive.google.com/drive/u/9/folders/1VTZGEVTYVMem9o1JEq36x905q-u2GVRG

**Comment by anadius** [comment]
I might add folder support so you can go into subfolders and back to main one but I won't add support for copying folders recursively. That's not the purpose of this tool. If you want that, use rclone.

**Comment by r9isgod8** [comment]
Yeah, that would work too. Thanks.

**Comment by anadius** [comment]
Implemented with a1ff8d127a2ee497f73693342c81a6b082d6c402.

**Comment by OgnistyPoland** [comment]
>I won't add support for copying folders recursively. That's not the purpose of this tool. If you want that, use rclone.
How can we copy encrypted links with rclone?

**Comment by Tithen-Firion** [comment]
You can't. I meant normal folders.

**Comment by anadius** [comment]
You can't. I meant normal folders.

**Comment by OgnistyPoland** [comment]
Now people are using your solution and there are no normal links, they are encrypted, so the option to copy the entire folder, not just files, would be useful

**Comment by anadius** [comment]
As I already said:
> I won't add support for copying folders recursively. That's not the purpose of this tool.

It's too many API requests one after another, high chance to hit the limit. It's too much code changes for too little gain, you can create a new folder and open it quickly in my tool already. If someone shares an encrypted link with more than one subfolder deep then blame them, this tool was never supposed to be used like that.

**Comment by OgnistyPoland** [comment]
> As I already said:
> 
> > I won't add support for copying folders recursively. That's not the purpose of this tool.
> 
> It's too many API requests one after another, high chance to hit the limit. It's too much code changes for too little gain, you can create a new folder and open it quickly in my tool already. If someone shares an encrypted link with more than one subfolder deep then blame them, this tool was never supposed to be used like that.

Okay, thanks for the answer

**Comment by acidburnxd** [comment]
> I might add folder support so you can go into subfolders and back to main one but I won't add support for copying folders recursively. That's not the purpose of this tool. If you want that, use rclone.

isn't you using rclone already :)

**Comment by anadius** [comment]
No, I'm not. I'm using their API credentials but I'm not using `rclone` itself.

**Comment by acidburnxd** [comment]
@anadius one off-topic question : I found this -- https://crypt.warezforums.com/
is it safe to use ? seems exact replica of yours !

**Comment by anadius** [comment]
I don't know, compare `main.obf.js` file with mine. Also, I removed the link since their main website seems to be about piracy.

**Comment by Kaylakaze** [comment]
Fucking amateur.
