### ISSUE TITLE
How far does it support static pages?

### ISSUE THREAD

**Issue by RkxBQ0Jyb3NUZXN0MUpTT04** [anadius/gd-efc#10]
I tested it on server works fine. I'm interested to know if it would support statically... 
It was giving no found page's decryption files in zip so can you guide a bit on which page does it scan so that I can try some stuff out to make it correct?

**Comment by anadius** [comment]
...what? What are you trying to do? The only static page is the `index.html` file I host here on GitHub.

**Comment by RkxBQ0Jyb3NUZXN0MUpTT04** [comment]
> 
> 
> ...what? What are you trying to do? The only static page is the `index.html` file I host here on GitHub.

was thinking of if it can all work statically? if not maybe the decryption server will need a server actually? but then the website hosted statically isn't generating the decryption files correctly...

**Comment by RkxBQ0Jyb3NUZXN0MUpTT04** [comment]
I'm pretty sure now something is going wrong for the build and index html css and js hosted on static site. It's decryption file encrypt.html is just html of 404 page i.e. `<title>Page Not Found</title>` 
reason why I;m wondering how far can the code be hosted statically..

**Comment by anadius** [comment]
If you want to host the decryption *page*, like [this](https://anadius.github.io/gd-efc/), and you want to have the `build.html` page working properly, you need to host `templates` folder too. That's why you get a 404 error pages. Because you host only some of the required files. Just host all files from this repo...

Files for decryption *server* MUST be hosted on a *server*. Either PHP one or Cloudflare Workers server. You can't host them statically.

**Comment by RkxBQ0Jyb3NUZXN0MUpTT04** [comment]
> 
> 
> If you want to host the decryption _page_, like [this](https://anadius.github.io/gd-efc/), and you want to have the `build.html` page working properly, you need to host `templates` folder too. That's why you get a 404 error pages. Because you host only some of the required files. Just host all files from this repo...
> 
> Files for decryption _server_ MUST be hosted on a _server_. Either PHP one or Cloudflare Workers server. You can't host them statically.

Oh! that was easy. Thanks. I didn't upload those... my bad. 
It makes the correct files on one static project where I could upload the files.
I have another project which is more restricted. So is there a way to add those templates into the html or js?

**Comment by anadius** [comment]
Yeah, just edit `build.js`. I'm not going to hold your hand, you can do it yourself.
