### ISSUE TITLE
How To Use ?

### ISSUE THREAD

**Issue by rahulmasal** [anadius/gd-efc#11]
Dear Team,

Please share step by step guide to host and install the script... and how to encrypt?

**Comment by anadius** [comment]
Just use the [build page](https://anadius.github.io/gd-efc/build.html). If you want to let other people encrypt links with your server too then check those optional boxes. If not, just use the `STATIC_ENCRYPTION/encrypt.html` file.

As for hosting - if you want to use CloudFlare Workers just copy the contents of `WORKER/worker.js`. If you want to host it on a PHP server just add `PHP/decrypt.php` and `PHP/.htaccess` files.

**Comment by rahulmasal** [comment]
i already copied files in php based hosting then what to do ?? in php based hosting ???

i want to encrypt links from same server then ??? but only for me not for others ??

please guide i am new in this :(

**Comment by rahulmasal** [comment]
![image](https://user-images.githubusercontent.com/22212803/116808777-4fd89d80-ab58-11eb-997d-57eaade2068d.png)

**Comment by rahulmasal** [comment]
![image](https://user-images.githubusercontent.com/22212803/116808918-0b99cd00-ab59-11eb-8253-e6a325f05df2.png)

files generated with all options selected !

**Comment by rahulmasal** [comment]
for encryption i want to use same php server for encryption then what to do??

![image](https://user-images.githubusercontent.com/22212803/116808963-67fcec80-ab59-11eb-8a2b-6d69fef9dcce.png)

**Comment by anadius** [comment]
If you want to host the decryption site (<https://anadius.github.io/gd-efc/>) then you're on your own. My tool was never meant to be rehosted somewhere else but people still do it. I'm not going to help with that.

If you want to have the encrypting available on your server but only for you - you're on your own. From the build page you get the static encryption which you can keep on your PC just for you or you can check the optional boxes and have it on your server for everyone. If you want something else - do it yourself.

Intended use: let's say you have a web server at `https://example.com/` and want the decryption server to be available at `https://example.com/decrypt`. Open the build page, set "decryption server" to `https://example.com/decrypt`, generate the key, click "download files". Then upload both of the files in `PHP` folder to your web server to `decrypt` subfolder. Copy Google Drive link (file or folder), encrypt it with `STATIC_ENCRYPTION/encrypt.html`. Then you can open that encrypted link on <https://anadius.github.io/gd-efc/>.

**Comment by rahulmasal** [comment]
Thanks for help!

and what about heroku ?? how to encrypt links if we deploy ??

**Comment by anadius** [comment]
As I already said, use the `STATIC_ENCRYPTION/encrypt.html` for encrypting links.

**Comment by rahulmasal** [comment]
PHP folder contains encrypt, decrypt and .htaccess files what are use of them?

**Comment by anadius** [comment]
The build page tells you what they are.
