### ISSUE TITLE
"Cannot read property 'importKey' of undefined"

### ISSUE THREAD

**Issue by MineRock** [anadius/gd-efc#12]
So in "https://anadius.github.io/gd-efc/build.html", I put in my server, it generated the key, I used PHP and disabled worker.js. Uploaded to drive. But it gives me the above error when trying to put in the gdrive link and clicking encrypt. Help?

**Comment by MineRock** [comment]
![image](https://user-images.githubusercontent.com/44112916/117657566-551c9480-b1b7-11eb-8988-91a91fb73304.png)

**Comment by anadius** [comment]
1. Don't host the `encrypt.html` file on your server. It contains the encryption key in plain text. Once someone reads it they can decrypt all your links and get the real URL. If you want to let people encrypt links from your server then check the right box on the build page.
2. Files must be hosted on HTTPS. That's a limitation of JavaScript. It requires HTTPS to use the cryptographic functions (like `crypto.subtle.importKey`).

**Comment by MineRock** [comment]
alright thanks
