### ISSUE TITLE
Fix Buttons

### ISSUE THREAD

**Issue by PBhadoo** [anadius/gd-efc#18]
Add class `btn-block` in buttons.

Change Button classes `col-12` etc to only `col`

This fixes alignment issues.

Check here at https://decrypt.hashhackers.com (doesn't fixes all buttons because they are coded in JS file)

**Comment by anadius** [comment]
I'm not going to change anything in my project because it doesn't look like you want in your fork. You can use JS too.

**Comment by PBhadoo** [comment]
Problem is that file is Obfuscated. I cannot find exactly where is the button classes in it. :(

**Comment by anadius** [comment]
So what? MutationObserver is your friend.
