### ISSUE TITLE
Rate limit exceeded even using my credentials.

### ISSUE THREAD

**Issue by Tesseractxss** [anadius/gd-efc#19]
Hi Anadius, how are you? First I want to thank you for the excellent site, it has helped me a lot these times.

But I have a little problem, I'm getting the message "Rate limit exceeded" all the time, even though I'm logged in with my credentials, to avoid this error.
:( I can copy the files, but all of a sudden I get "Rate limit exceeded" Is there any way to solve this? If it is not possible, there would be no way to add something to the site, so that it would ignore the files that were copied, and continue copying the files that haven't yet? Because when you click "copy" again, it starts copying all the files from the beginning, and that creates copies of files that have already been copied.

Thanks again for the website! \ õ

**Comment by anadius** [comment]
You're not using custom credentials. Or you share them together with other people. Because the quotas are:
- 20000 queries per 100 seconds
- 1000000000 queries per day

So I really don't know how you hit the limit.

And no, I can't add what you want because that would break the old servers. So everyone would have to update their server code.

**Comment by Tesseractxss** [comment]
It's been 2 days since it started, on all my accounts. I even created a new account, and the problem persists. I am not using custom credentials, nor do I share them with anyone. I don't know what's going on, because even the new account isn't working, the error "Rate limit exceeded" always appears.

**Comment by anadius** [comment]
> even though I'm logged in with my credentials, to avoid this error

> I am not using custom credentials

So are you, or are you not? When you click on the "Select account" button is "Use custom OAuth credentials" box checked or not?

**Comment by Tesseractxss** [comment]
Sorry for my english, I'm using google translator.

I enter the site, click "Select Account" I check the box "Use custom OAuth credentials"

I put the "User ID, and also the Client secret" Then I go to "Get auth" I select the account where I got the "OAuth credentials" I give permission, I get the generated code and paste it in "Get auth" and continue. When I start to copy the files from a link to Team Drive, I just get the message "Rate limit exceeded" even with everything correct. This started to occur on 04/22/2022. It used to work normally on any account of mine, but now it doesn't even work on new accounts.

Print screen ↓ 

`https://i.ibb.co/7t1G8kV/image.png`

**Comment by anadius** [comment]
You didn't click the "Save" button so you're not using your custom credentials...

**Comment by Tesseractxss** [comment]
Sorry for the delay in responding, it was late here yesterday so I fell asleep.

I was clicking on save, but on the print I hadn't clicked on it yet.

For some reason today I was able to use your site without "Rate limit" error but on another account. On the account I was trying, it doesn't work. When I save the credentials, I can't generate the authentication code, I get authorization error "404" I can only use it if I don't save the credentials. I believe the problem is my account, for some reason google is preventing me from using my credentials even if I create new ones.

That's weird, but since it's working on another account it's fine. Thank you for your attention, and sorry for anything.
