### ISSUE TITLE
Some enhancements needed in My drive area

### ISSUE THREAD

**Issue by Medow** [anadius/gd-efc#2]
Hello:
Thanks for making this tool, it is great.
I have 3 suggestions i hope you find the time to make:

1. For now the code only showed the files copied by your code, and i get around this by deleting `"+and+appProperties+has+%7B+key%3D'createdWithDdEfc'+and+value%3D'1'+%7D"` part.

2. The My drive area only showed the files not folders, i hope you can edit it to show all files and folders in current directory with the option for making a new folder.

3. To clone a file users should give the folder id they need to copy files in it (If they don't wanna save it in root folder), this mean users should create the folder and get the folder id. I suggest you to get the current directory the user browse and copy to it. For example if he create a new folder in step 2 above and inter to it, the new files will copy to that folder.

Thank you very much for making this.

Best regards.

**Comment by anadius** [comment]
1. That's by the design. I'm not changing it. If you want to browse all files just go to your Drive...

Folders support (2. and 3.) is in plans, no ETA though.

**Comment by anadius** [comment]
1. That's by the design. I'm not changing it. If you want to browse all files just go to your Drive...

Folders support (2. and 3.) is in plans, no ETA though.

**Comment by anadius** [comment]
Implemented with 9ee57dfe8692eddc646ae3dc41bf026951e994d1.
