### ISSUE TITLE
Website showing "No Decryption server found" after pasting encrypted link

### ISSUE THREAD

**Issue by VishmaPratimDasHere** [anadius/gd-efc#22]

**Comment by anadius** [comment]
Then report that to person who shared the encrypted link, not to me. I just made the tool.

**Comment by abhijeet834u** [comment]
Hi, the Server is sending the JSON response but the application is getting Error Code 503. Can you please check? 
Chrome is showing the following Reason: CORS header 'Access-Control-Allow-Origin' missing

**Comment by anadius** [comment]
**Then report that to person who shared the encrypted link, not to me. I just made the tool.**
