### ISSUE TITLE
No working decryption server found.

### ISSUE THREAD

**Issue by grandpa1946** [anadius/gd-efc#26]
can i do anything about it?
if you need the Encrypted folder ID or normal folder link i can provide it to you

**Comment by anadius** [comment]
No. If the person who shared the link messed up and their server is down - tell that to them, not me.

**Comment by grandpa1946** [comment]
> No. If the person who shared the link messed up and their server is down - tell that to them, not me.

i tried to base64decode the url, and the first part led to a mirror of this repo's website, and rest was other i think "useful" information
if you want, i can share you the encoded url, maybe that would help me

**Comment by anadius** [comment]
No, don't send any links here or I'll block you. Like I said, report that to the person who shared the link.
