### ISSUE TITLE
New type of error 

### ISSUE THREAD

**Issue by Ex-Communicad0** [anadius/gd-efc#27]
on rclone authentication, it looks like instead of rate limit error, its now showing this error

can you censor the project number or remove it so that rclone authentication is safe

ERROR: Quota exceeded for quota metric 'Queries' and limit 'Queries per minute' of service 'drive.googleapis.com' for consumer 'project_number:202264815644'. 

try this here 

\<snip\>

dec0de it base64

note: everything works fine after 2nd or 3rd try, its just this error looks vulnerable for rclone project

**Comment by anadius** [comment]
You mean the project number that's posted publicly on rclone's github and their own forums makes it vulnerable because it's displayed in my error message? Okay. And don't post your links here. Next time I'll block you from interacting with this repo.
