### ISSUE TITLE
Error: 520

### ISSUE THREAD

**Issue by Ex-Communicad0** [anadius/gd-efc#28]
Error: error code: 520

getting this error on old links generated, it was working fine till a week ago.

for newly generated links working fine, keys are same

any guidance or solution please thank you 

the problem is generated many links before (parmanent) dont want to replace everything again is there any solution for that

**Comment by anadius** [comment]
Do you use Cloudflare Workers as your decryption server? I noticed that if the decryption server uses the old "Service Worker" format it throws this error a lot and works only some of the times.
 
I updated the workers code in this commit: 34fb13d

The easiest way to use the new code is as follows:
1. Generate new files on https://anadius.github.io/gd-efc/build.html (use the same encryption key as earlier)
2. Create a new Cloudflare Worker and use the new code.
3. Swap the names of the old and the new worker.

There's a chance it was just a coincidence and Google simply blocks some requests, for unknown reason. Give it a try though.

**Comment by Ex-Communicad0** [comment]
1. pasted new code, note: new code was not deploying on workers js so i had to change this code  

> w.b64 = b64;
> return b64;
> })(this);

to this 

> self.b64 = b64;
> return b64;
> })(self);


also changed the decrypt php code 

restarted the server no luck

tried disabling the cloudflare proxy on domain still same error on old links :(

**Comment by anadius** [comment]
1. Oops, my bad. Remove `w.b64=b64;`, don't make any other changes. And you can't use that code on an old worker because it's missing some files and won't even let you save. And don't touch the PHP code, I haven't changed a single bit of it.
2. No. Why would it apply to only new links? Generate new code on my website **with the same encryption key** and **with the same decryption domains** as the first time. Make a new worker with the new code and **swap the worker names, in Cloudflare dashboard**.

**Comment by Ex-Communicad0** [comment]
Thanks, swaping the workers solved the issue now.

but i hosted decrypt script on my own subdomain where i was getting bad request on console is it because it is blocked? 

i mean disabled the cloudflare workers before then tried with only hosted server domain but its producing same issue (bad request) , if cloudflare hits limit the issue will popup again :( maybe

**Comment by anadius** [comment]
I don't know what you hosted and where. I don't know if Google blocked some IP addresses and that's why it throws 520 error. All I know is that the change I did helped and nobody reported getting this error since I swapped the workers.
