### ISSUE TITLE
Why main.js obfuscated?

### ISSUE THREAD

**Issue by Medow** [anadius/gd-efc#3]
Hi:
Your code is turning to be a similar to closed code by obfuscated the main.js file.
Users of your code have many needs and they needs to edit the code according to that needs which is impossible now.
I hope you make it open again.
Thanks.

**Comment by cryptdrive** [comment]
It has been obfuscated so users can't edit the footer and remove his credits . Some people were selling the script m

**Comment by anadius** [comment]
Pretty much this. People stealing and selling my script. Either open a new issue if you want some new feature implemented or grab the last version before obfuscating [from here](https://github.com/anadius/gd-efc/tree/bcad0c4f4a8e0902e19200a94b9cedad3e856f13) and implement it yourself.

**Comment by dudeisbrendan03** [comment]
> Pretty much this. People stealing and selling my script. Either open a new issue if you want some new feature implemented or grab the last version before obfuscating [from here](https://github.com/anadius/gd-efc/tree/bcad0c4f4a8e0902e19200a94b9cedad3e856f13) and implement it yourself.

You've also obfuscated Google OAuth/app data so people are unable to modify the client you're sending them to.

I'm all for keeping your credit but I don't want you to be able to have possible access to the data of all the users who use the app.

**Comment by anadius** [comment]
If you want an option to change the client ID and secret - create a new issue and request it. I use credentials from `rclone` so I don't have access to anything.

You can check yourself what data is sent from this app and where to. When you use normal links it contacts just google servers. When you use encrypted link it sends your access token to the decryption server. And as the instructions say, access token gives them access to your whole gdrive for 1 hour. You can also read the default code of the decrypt server and see that it doesn't store that token - but obviously someone can modify it. So use encrypted links from trusted people only OR use a dummy acc like the warning at the top of my app says.
